// src/lib/components/AnimeGrid.svelte
<script lang="ts">
  import type { AnimeCard } from '#lib/shared/types'
  import { fetchAnimePage } from '#lib/api'
  import { isServerError } from '#lib/error'
  import { progressMap, syncProgressMap } from '#lib/progress-map'
  import { onMount } from 'svelte'
  import AnimePosterCard from './AnimePosterCard.svelte'
  import EmptyState from './EmptyState.svelte'

  interface PageData {
    anime: AnimeCard[]
    totalPages: number
  }

  let {
    pageType,
    initialData,
    showDay = true,
    nextPageType = undefined,
    nextInitialData = undefined,
    nextShowDay = false,
  }: {
    pageType: 'ONGOING' | 'COMPLETED'
    initialData: PageData
    showDay?: boolean
    nextPageType?: 'ONGOING' | 'COMPLETED'
    nextInitialData?: PageData
    nextShowDay?: boolean
  } = $props()

  let sentinelRef: HTMLDivElement | null = $state(null)
  let gridRef: HTMLDivElement | null = $state(null)
  let primaryPages = $state<PageData[]>([initialData])
  let nextPages = $state<PageData[]>([])
  let primarySize = $state(1)
  let nextSize = $state(0)
  let loading = $state(false)
  let loadError = $state(false)
  let loadServerError = $state(false)

  const primaryAnime = $derived(primaryPages.flatMap(d => d.anime))
  const totalPages = $derived(primaryPages[0]?.totalPages ?? 1)
  const primaryEnd = $derived(primarySize >= totalPages)
  const nextAnime = $derived(primaryEnd ? nextPages.flatMap(d => d.anime) : [])
  const nextTotalPages = $derived(nextPages[0]?.totalPages ?? 1)
  const nextEnd = $derived(!nextPageType || (primaryEnd && nextSize >= nextTotalPages))
  const isEnd = $derived(primaryEnd && nextEnd)

  const displayCards = $derived([
    ...primaryAnime.map(anime => ({ anime, isFromNext: false })),
    ...nextAnime.map(anime => ({ anime, isFromNext: true })),
  ].map(({ anime, isFromNext }) => {
    const progress = progressMap.get(anime.malId)
    const resumeTo = progress ? `/anime/${anime.malId}/${progress.episodeNumber}` : undefined
    const showDate = anime.day && (isFromNext ? nextShowDay : showDay)
    const latest = Number(anime.episode.match(/\d+/)?.[0])
    const num = anime.episode.match(/\d+/)?.[0]
    return {
      anime,
      badge: num ? `${num} Eps` : '',
      newEpisode: progress?.latestEpisode !== undefined && Number.isFinite(latest) && latest > progress.latestEpisode,
      to: `/anime/${anime.malId}`,
      resumeTo,
      subtitle: progress
        ? `Lanjutkan EP ${progress.episodeNumber}`
        : showDate
          ? anime.date
            ? `${anime.day} · ${anime.date}`
            : anime.day
          : anime.date,
      progressPct: progress && progress.duration > 0 ? (progress.currentTime / progress.duration) * 100 : undefined,
    }
  }))

  const hasAnyCard = $derived(primaryAnime.length > 0 || nextAnime.length > 0)
  const showPlane = $derived(loadError && loadServerError && !hasAnyCard)

  async function loadNextAvailablePage() {
    if (!primaryEnd) {
      const nextPage = primarySize + 1
      primaryPages = [...primaryPages, await fetchAnimePage(fetch, pageType, nextPage)]
      primarySize = nextPage
      return
    }
    if (nextPageType && !nextEnd) {
      const nextPage = nextSize + 1
      const data =
        nextPage === 1 && nextInitialData
          ? nextInitialData
          : await fetchAnimePage(fetch, nextPageType, nextPage)
      nextPages = [...nextPages, data]
      nextSize = nextPage
    }
  }

  async function loadMore() {
    if (loading || isEnd) return
    loading = true
    loadError = false
    loadServerError = false
    let loaded = false
    try {
      await loadNextAvailablePage()
      loaded = true
    } catch (err) {
      loadError = true
      loadServerError = isServerError(err)
    } finally {
      loading = false
    }
    if (loaded) await fillViewport()
  }

  function isSentinelNearViewport() {
    if (!sentinelRef || isEnd) return false
    const rect = sentinelRef.getBoundingClientRect()
    return rect.top <= window.innerHeight * 3 && rect.bottom >= -800
  }

  async function fillViewport() {
    await new Promise(resolve => requestAnimationFrame(resolve))
    if (isSentinelNearViewport()) void loadMore()
  }

  let observer: IntersectionObserver | null = null

  onMount(() => {
    void syncProgressMap()
    observer = new IntersectionObserver(
      entries => {
        if (entries.some(entry => entry.isIntersecting)) void loadMore()
      },
      { rootMargin: '200% 0px' },
    )
    if (sentinelRef) observer.observe(sentinelRef)

    const onVisibility = () => {
      if (document.visibilityState === 'visible') void syncProgressMap()
    }
    document.addEventListener('visibilitychange', onVisibility)
    void fillViewport()

    return () => {
      observer?.disconnect()
      document.removeEventListener('visibilitychange', onVisibility)
    }
  })
</script>

<div>
  <div
    bind:this={gridRef}
    class="grid grid-cols-2 [@media(min-width:640px)_and_(min-height:601px)]:[grid-template-columns:repeat(auto-fill,minmax(200px,1fr))] [@media(min-width:640px)_and_(max-height:600px)]:[grid-template-columns:repeat(auto-fill,minmax(130px,1fr))] gap-4"
  >
    {#each displayCards as card, i (card.anime.malId + '-' + i)}
      <AnimePosterCard
        to={card.to}
        thumbnail={card.anime.thumbnail}
        title={card.anime.title}
        badge={card.badge}
        newEpisode={card.newEpisode}
        subtitle={card.subtitle}
        resumeTo={card.resumeTo}
        progressPct={card.progressPct}
        priority={i < 6}
      />
    {/each}
  </div>

  {#if showPlane}
    <EmptyState />
  {/if}
  <div bind:this={sentinelRef} class="py-4">
    {#if loadError && !showPlane}
      <button type="button" class="block mx-auto text-sm text-zinc-400 hover:text-white" onclick={loadMore}>
        Gagal memuat anime. Coba lagi
      </button>
    {/if}
  </div>
</div>

// app/components/AnimeGrid.vue
<script setup lang="ts">
import type { AnimeCard } from '~/types'

interface PageData {
  anime: AnimeCard[]
  totalPages: number
}

const props = withDefaults(
  defineProps<{
    pageType: 'ONGOING' | 'COMPLETED'
    initialData: PageData
    showDay?: boolean
    nextPageType?: 'ONGOING' | 'COMPLETED'
    nextInitialData?: PageData
    nextShowDay?: boolean
  }>(),
  {
    showDay: true,
    nextPageType: undefined,
    nextInitialData: undefined,
    nextShowDay: false,
  },
)

const sentinelRef = shallowRef<HTMLDivElement | null>(null)
const gridRef = shallowRef<HTMLDivElement | null>(null)
const cols = ref(2)
const gridState = useState<{
  primaryPages: PageData[]
  nextPages: PageData[]
  primarySize: number
  nextSize: number
}>(`anime-grid:${props.pageType}:${props.nextPageType ?? ''}`, () => ({
  primaryPages: [props.initialData],
  nextPages: [],
  primarySize: 1,
  nextSize: 0,
}))
const loading = ref(false)
const loadError = ref(false)
const loadServerError = ref(false)
const { progressMap, syncProgress } = useAnimeProgressMap(() => [])

onMounted(() => {
  void syncProgress()
  const onVisibility = () => {
    if (document.visibilityState === 'visible') void syncProgress()
  }
  document.addEventListener('visibilitychange', onVisibility)
  onBeforeUnmount(() => document.removeEventListener('visibilitychange', onVisibility))
})

watch(
  () => props.initialData,
  data => {
    if (gridState.value.primaryPages[0]?.anime.length) return
    gridState.value.primaryPages = [data]
    gridState.value.primarySize = 1
    gridState.value.nextPages = []
    gridState.value.nextSize = 0
  },
)

const primaryAnime = computed(() => gridState.value.primaryPages.flatMap(d => d.anime))
const totalPages = computed(() => gridState.value.primaryPages[0]?.totalPages ?? 1)
const primaryEnd = computed(() => gridState.value.primarySize >= totalPages.value)
const nextAnime = computed(() => (primaryEnd.value ? gridState.value.nextPages.flatMap(d => d.anime) : []))
const nextTotalPages = computed(() => gridState.value.nextPages[0]?.totalPages ?? 1)
const nextEnd = computed(
  () => !props.nextPageType || (primaryEnd.value && gridState.value.nextSize >= nextTotalPages.value),
)
const isEnd = computed(() => primaryEnd.value && nextEnd.value)

const displayAnime = computed(() => [
  ...primaryAnime.value.map(anime => ({ anime, isFromNext: false })),
  ...nextAnime.value.map(anime => ({ anime, isFromNext: true })),
])
const displayCards = computed(() =>
  displayAnime.value.map(({ anime, isFromNext }) => {
    const progress = progressMap.value.get(anime.malId)
    const resumeTo = progress ? `/anime/${anime.malId}/${progress.episodeNumber}` : undefined
    const showDate = anime.day && (isFromNext ? props.nextShowDay : props.showDay)
    const latest = Number(anime.episode.match(/\d+/)?.[0])
    return {
      anime,
      badge: episodeBadge(anime.episode),
      newEpisode: progress?.latestEpisode !== undefined && Number.isFinite(latest) && latest > progress.latestEpisode,
      to: `/anime/${anime.malId}`,
      resumeTo,
      subtitle: progress
        ? `Lanjutkan EP ${progress.episodeNumber}`
        : showDate
          ? anime.date
            ? `${anime.day} · ${anime.date}`
            : anime.day
          : anime.date,
      progressPct: progress && progress.duration > 0 ? (progress.currentTime / progress.duration) * 100 : undefined,
    }
  }),
)
const hasAnyCard = computed(() => displayAnime.value.length > 0)
const showPlane = computed(() => loadError.value && loadServerError.value && !hasAnyCard.value)

async function fetchPage(type: 'ONGOING' | 'COMPLETED', page: number): Promise<PageData> {
  return fetchAnimePage(type, page)
}

async function loadPrimaryPage() {
  const nextPage = gridState.value.primarySize + 1
  gridState.value.primaryPages.push(await fetchPage(props.pageType, nextPage))
  gridState.value.primarySize = nextPage
}

async function loadNextPage() {
  const nextPage = gridState.value.nextSize + 1
  const nextPageType = props.nextPageType
  const data =
    nextPage === 1 && props.nextInitialData
      ? props.nextInitialData
      : nextPageType
        ? await fetchPage(nextPageType, nextPage)
        : null
  if (!data) return
  gridState.value.nextPages.push(data)
  gridState.value.nextSize = nextPage
}

async function loadNextAvailablePage() {
  if (!primaryEnd.value) return loadPrimaryPage()
  if (props.nextPageType && !nextEnd.value) return loadNextPage()
}

async function loadMore() {
  await loadGridPage({
    loading,
    loadError,
    loadServerError,
    isEnd,
    load: loadNextAvailablePage,
    afterLoad: () => fillGridViewport(isSentinelNearViewport, loadMore),
  })
}

const { isSentinelNearViewport } = useInfiniteGridObserver({ gridRef, sentinelRef, cols, isEnd, loadMore })

function episodeBadge(episode: string) {
  const num = episode.match(/\d+/)?.[0]
  return num ? `${num} Eps` : ''
}
</script>

<template>
  <div>
    <div ref="gridRef" class="grid grid-cols-2 [@media(min-width:640px)_and_(min-height:601px)]:[grid-template-columns:repeat(auto-fill,minmax(200px,1fr))] [@media(min-width:640px)_and_(max-height:600px)]:[grid-template-columns:repeat(auto-fill,minmax(130px,1fr))] gap-4">
      <AnimePosterCard
        v-for="({ anime, badge, newEpisode, to, resumeTo, subtitle, progressPct }, i) in displayCards"
        :key="`${anime.malId}-${i}`"
        :to="to"
        :thumbnail="anime.thumbnail"
        :title="anime.title"
        :badge="badge"
        :new-episode="newEpisode"
        :subtitle="subtitle"
        :resume-to="resumeTo"
        :progress-pct="progressPct"
        :priority="i < 6"
      />
    </div>

    <EmptyState v-if="showPlane" />
    <div ref="sentinelRef" class="py-4">
      <button v-if="loadError && !showPlane" type="button" class="block mx-auto text-sm text-zinc-400 hover:text-white" @click="loadMore">
        Gagal memuat anime. Coba lagi
      </button>
    </div>
  </div>
</template>
