// app/components/AnimeSheetHost.vue
<script setup lang="ts">
import type { AnimeDetail } from '~/types'

const sheet = useAnimeSheet()
const open = computed(() => sheet.state.value.open)
const anime = ref<AnimeDetail | null>(null)
const sheetRef = ref<{ requestClose: () => void } | null>(null)
let fromPopstate = false

watch(() => sheet.state.value.malId, async (malId) => {
  anime.value = null
  if (!malId) return
  try {
    anime.value = await $fetch<AnimeDetail>(`/api/anime/${malId}`)
  } catch {
    anime.value = null
    sheet.markClosed()
    sheet.dropFakeEntry()
  }
}, { immediate: true })

watch(() => sheet.state.value.closing, (closing) => {
  if (!closing) return
  fromPopstate = true
  sheetRef.value?.requestClose()
})

function onClosed() {
  const goBack = !fromPopstate && sheet.hasFakeEntry()
  sheet.markClosed()
  if (goBack) {
    sheet.dropFakeEntry()
    history.back()
  }
  fromPopstate = false
}
</script>

<template>
  <AnimeDetailSheet v-if="open" ref="sheetRef" :thumbnail="anime?.thumbnail" :title="anime?.title" @close="onClosed">
    <AnimeDetailContent v-if="anime" :anime="anime" hide-back />
  </AnimeDetailSheet>
</template>

// src/lib/components/AnimeSheetHost.svelte
<script lang="ts">
  import type { AnimeDetail } from '#lib/shared/types'
  import { fetchAnimeDetail } from '#lib/api'
  import { animeSheet, dropFakeEntry, hasFakeEntry, markAnimeSheetClosed } from '#lib/anime-sheet.svelte'
  import AnimeDetailContent from './AnimeDetailContent.svelte'
  import AnimeDetailSheet from './AnimeDetailSheet.svelte'

  let anime = $state<AnimeDetail | null>(null)
  let sheetRef: AnimeDetailSheet | null = $state(null)
  let fromPopstate = false
  let loadedMalId = 0

  $effect(() => {
    const malId = animeSheet.malId
    if (malId === loadedMalId) return
    loadedMalId = malId
    anime = null
    if (!malId) return
    let cancelled = false
    fetchAnimeDetail(fetch, malId)
      .then(detail => {
        if (!cancelled) anime = detail
      })
      .catch(() => {
        if (cancelled) return
        anime = null
        markAnimeSheetClosed()
        dropFakeEntry()
      })
    return () => {
      cancelled = true
    }
  })

  $effect(() => {
    if (!animeSheet.closing) return
    fromPopstate = true
    sheetRef?.requestClose()
  })

  function onClosed() {
    const goBack = !fromPopstate && hasFakeEntry()
    markAnimeSheetClosed()
    if (goBack) {
      dropFakeEntry()
      history.back()
    }
    fromPopstate = false
  }
</script>

{#if animeSheet.open}
  <AnimeDetailSheet bind:this={sheetRef} thumbnail={anime?.thumbnail} title={anime?.title} onclose={onClosed}>
    {#if anime}
      <AnimeDetailContent {anime} hideBack />
    {/if}
  </AnimeDetailSheet>
{/if}
